apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appointment-booking.fullname" . }}
  labels:
    {{- include "appointment-booking.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appointment-booking.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "appointment-booking.labels" . | nindent 8 }}
    spec:
      containers:
        - name: notification-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.SPRING_DATASOURCE_URL | quote }}
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.SPRING_KAFKA_BOOTSTRAP_SERVERS | quote }}
            {{- include "appointment-booking.otelEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
